account/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='user_login'),
    path('logout/', views.logout, name='user_logout'),
    path('register/', views.Register.as_view(), name='user_register'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),

    path('home/', views.AccountHomeView.as_view(), name='home'),
    path('profile/edit/', views.profile_normal_user_view, name='profile-edit'),
    path('search/', views.article_search, name='search'),
    path('article/create', views.ArticleCreateView.as_view(), name='article-create'),
    path('article/update/<int:pk>', views.ArticleUpdateView.as_view(), name='article-update'),
    path('article/delete/<int:pk>', views.ArticleDeleteView.as_view(), name='article-delete'),
    path('profile', views.ProfileUpdateView.as_view(), name='profile'),

]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='blog_detail'),
    path('list',views.PostListView.as_view(), name='blog_list'),
    path('category/<int:pk>', views.category_detail.as_view(), name='cat_list'),
    path('tag/<int:pk>', views.tag_detail.as_view(), name='tag_list'),
    path('comment/delete/<int:pk>/<slug:slug>', views.DeleteCommentView.as_view(), name='comment_delete'),
    path('search', views.SearchView.as_view(), name='search'),
    path('contact', views.ContactsView.as_view(), name='contact'),
    path('like/<slug:slug>/<int:pk>', views.LikeView.as_view(), name='like_article'),
    path('favorite/<int:id>', views.FavoriteView.as_view(), name='favorite_article'),
    path('favorite/list', views.FaveView.as_view(), name='favorite_list'),
    path('preview/<int:pk>', views.ArticlePreviewView.as_view(), name='article_preview'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('articles/', include('blogs.urls', namespace='blog')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from account.models import User
from django.db import models
from django.urls import reverse
from django.utils.html import format_html


# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=100, blank=True, null=True, unique=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=100, blank=True, null=True, unique=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    ##################
    # Custom Manager.#
    #################


# class ArticleManger(models.Manager):
#     def get_queryset(self):
#         return super(ArticleManger, self).get_queryset().filter(is_published = True)

class Article(models.Model):
    STATUS = [
        ("Publish", "انتشار یافته"),
        ("Unpublished", "انتشار نیافته "),
        ("Draft", "پیش نویس"),
        ("I", "درحال بررسی"),
        ("b", "برگشت خورده")
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='articles')
    tag = models.ManyToManyField(Tag, related_name='articles')
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=100000)
    image = models.ImageField(upload_to='images/articles')
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, blank=True, null=True, unique=True)
    updated = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False)
    favorite = models.ManyToManyField(User, default=None, blank=True, null=True, related_name='favorite')
    status = models.CharField(max_length=20, choices=STATUS, default="Draft")
    hints = models.ManyToManyField('IPAddress', through='ArticleHint', blank=True, null=True,
                                   related_name='hints')

    # custom_manager = ArticleManger()

    def __str__(self):
        return self.title

    def image_tag(self):
        return format_html("<img src='{}' width=100 height=100 style='border-radius: 10px;'>".format(self.image.url))

    image_tag.short_description = 'image'

    ###########################################################################################
    # Save method : if title send database this method run and create new tag from title name.#
    ###########################################################################################

    class Meta:
        ordering = ('-created',)
    # def save(self, *args, **kwargs):
    #     if self.title:
    #         super(Article, self).save(args, kwargs)
    #         Tag.objects.create(title=self.title)
    #


# Class Comment.
class Comment(models.Model):
    articles = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    body = models.TextField(max_length=1000)
    created_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body


# Contact Form.
class Contact(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=1000)
    email = models.EmailField(max_length=1000)
    number = models.IntegerField(verbose_name='Enter your number', null=True, blank=True)
    subject = models.CharField(max_length=1000)
    message = models.TextField(max_length=1000000)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name


class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()


class ArticleHint(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_hint')
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE, related_name='article_hint')
    created = models.DateTimeField(auto_now_add=True)

blogs/forms.py
from django import forms
from django.core import validators

from blogs.models import Contact, Comment


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

blogs/views.py
from datetime import timezone, timedelta, datetime

from account.mixins import AuthorAccessMixin
from account.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.core.paginator import Paginator
from django.contrib import messages
from django.views.generic import ListView, FormView, CreateView, DetailView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from blogs.forms import ContactForm, CommentForm
from blogs.models import Article, Category, Tag, Comment, Contact, Like
from django.db.models import Count, Q


# Create your views here


class PostDetailView(View):
    form_class = CommentForm

    def get(self, request, slug):
        article = get_object_or_404(Article, slug=slug)
        categories = Category.objects.all()
        resent_article = Article.objects.filter(status='Publish').order_by("-updated")[:3]
        ip_address = request.user.ip_address
        if ip_address not in article.hints.all():
            article.hints.add(ip_address)
        if request.user.is_authenticated:

            if request.user.likes.filter(article__slug=slug, user_id=request.user.id).exists():
                is_likes = True
            else:
                is_likes = False

            if article.favorite.filter(id=request.user.id).exists():
                is_fave = True
            else:
                is_fave = False

            return render(request, 'blogs/article_detail.html',
                          {'article': article, 'resent_article': resent_article, 'categories': categories,
                           'is_likes': is_likes, 'is_fave': is_fave})

        else:
            return render(request, 'blogs/article_detail.html',
                          {'article': article, 'resent_article': resent_article, 'categories': categories})

    def post(self, request, slug):
        article = get_object_or_404(Article, slug=slug)
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        comment = Comment.objects.create(body=body, articles=article, user=request.user, parent_id=parent_id)
        comment.save()
        messages.success(request, 'Youre comment is added successfully', 'success')
        return redirect('blog:blog_detail', article.slug)


class DeleteCommentView(View):
    def get(self, request, pk, slug):
        article = get_object_or_404(Article, slug=slug)
        comment = get_object_or_404(Comment, id=pk)
        if comment.user.id == request.user.id:
            comment.delete()
            messages.success(request, 'Youre comment is delete', 'warning')
            return redirect('blog:blog_detail', article.slug)


class PostListView(View):
    def get(self, request):
        last_month = datetime.today() - timedelta(days=30)
        articles = Article.objects.filter(status="Publish").annotate(
            count=Count('hints', filter=Q(article_hint__created__gt=last_month))).order_by('-count', '-created')[:5]
        tags = Tag.objects.all()
        categories = Category.objects.all()
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 3)
        objects_list = paginator.get_page(page_number)

        return render(request, 'blogs/article_list.html',
                      {'articles': objects_list, 'tags': tags,
                       'categories': categories})


# class PostListView(ListView):
#     model = Article
#     paginate_by = 1
#     context_object_name = 'articles'
#     queryset = Article.objects.filter(is_published=True)
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super(PostListView)

class category_detail(View):
    def get(self, request, pk=None):
        category = get_object_or_404(Category, id=pk)
        articles = category.articles.all()
        tags = Tag.objects.all()
        categories = Category.objects.all()
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 1)
        objects_list = paginator.get_page(page_number)

        return render(request, "blogs/article_list.html",
                      {'articles': objects_list, 'category': category, 'tags': tags, 'categories': categories})


class tag_detail(View):
    def get(self, request, pk=None):
        tag = get_object_or_404(Tag, id=pk)
        articles = tag.articles.all()
        tags = Tag.objects.all()
        categories = Category.objects.all()
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 1)
        objects_list = paginator.get_page(page_number)

        return render(request, 'blogs/article_list.html',
                      {'articles': objects_list, 'tag': tag, 'tags': tags, 'categories': categories})


class SearchView(View):
    def get(self, request):
        q = request.GET.get('q')
        articles = Article.objects.filter(title__icontains=q)
        tags = Tag.objects.all()
        categories = Category.objects.all()
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 1)
        objects_list = paginator.get_page(page_number)

        return render(request, 'blogs/article_list.html',
                      {'articles': objects_list, 'q': q, 'tags': tags, 'categories': categories})


# class ContactsView(View):
#     form_class = ContactForm
#
#     def get(self, request):
#         return render(request, 'blogs/contact.html')
#
#     def post(self, request):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             new = form.save(commit=False)
#             new.user = request.user
#             new.save()
#             messages.success(request, 'Youre contact is sucess', 'success')
#             return redirect('blog:contact')
#         return render(request, 'blogs/contact.html')
#

class ContactsView(CreateView):
    template_name = 'blogs/contact.html'
    model = Contact
    fields = "__all__"
    success_url = reverse_lazy('blog:contact')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super().form_valid(form)


class LikeView(LoginRequiredMixin, View):
    """
    Create object like for post
    and check member has like this post or no
    """

    def get(self, request, slug, pk):
        try:
            like = Like.objects.get(article__slug=slug, user_id=request.user.id)
            like.delete()
            return JsonResponse({'response': 'dislike'})
        except:
            Like.objects.create(article_id=pk, user_id=request.user.id)
            return JsonResponse({'response': 'like'})


class FavoriteView(LoginRequiredMixin, View):
    """
    Add favorite article to favorite
    """

    def get(self, request, id):
        blog = Article.objects.get(id=id)

        if blog.favorite.filter(id=request.user.id).exists():
            blog.favorite.remove(request.user.id)
            return JsonResponse({'response': 'deleted'})
        else:
            blog.favorite.add(request.user.id)
            return JsonResponse({'response': 'added'})


class FaveView(ListView):
    """
    List Favorite Article
    """
    template_name = 'blogs/favorite.html'
    model = Article
    paginate_by = 10
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.filter(favorite=self.request.user)


class ArticlePreviewView(LoginRequiredMixin, AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)

blogs/templates/blogs/article-list.html
{% extends 'base.html' %}
{% load static %}

{% block contact %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ article.category }}</span>
                                            <a href="{% url 'blog:blog_detail' article.slug %}">
                                                <h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.author }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body|truncatewords:24 }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            {% for tag in article.tag.all %}
                                                                <li>
                                                                    <a href="{% url 'blog:tag_list' tag.id %}">{{ tag.title }}</a>,
                                                                </li>
                                                            {% endfor %}


                                                        </ul>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            {% endfor %}
                            <div class="col-lg-12">
                                {% if articles.has_other_pages %}
                                    <ul class="page-numbers">
                                        {% if articles.has_previous %}
                                            <li><a href="?page={{ articles.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                                                    class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}

                                        {% for i in articles.paginator.page_range %}

                                            {% if articles.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% endif %}

                                        {% endfor %}

                                        {% if articles.has_next %}
                                            <li><a href="?page={{ articles.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                                                    class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                {% include 'inc/sidebar_home_listpost.html' %}

            </div>
        </div>
    </section>
{% endblock %}

blogs/templates/blogs/contact.html
{% extends 'base.html' %}
{% block contact %}


    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>contact us</h4>
                            <h2>let’s stay in touch!</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->



    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    {% if request.user.is_authenticated %}
                                        {% include 'inc/messages.html' %}
                                        <div class="content">
                                            <form id="contact" action="" method="post">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-md-6 col-sm-12">
                                                        <fieldset>
                                                            <input name="name" type="text" id="name"
                                                                   placeholder="Your name" required="">
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-md-6 col-sm-12">
                                                        <fieldset>
                                                            <input name="email" type="text" id="email"
                                                                   placeholder="Your email" required="">
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-md-6 col-sm-12">
                                                        <fieldset>
                                                            <input name="number" type="number" id="number"
                                                                   placeholder="(+98)" required="">
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-md-12 col-sm-12">
                                                        <fieldset>
                                                            <input name="subject" type="text" id="subject"
                                                                   placeholder="Subject">
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <textarea name="message" rows="6" id="message"
                                                                      placeholder="Your Message" required=""></textarea>
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Send Message
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="sidebar-item contact-information">
                                                <div class="sidebar-heading">
                                                    <h2>contact information</h2>
                                                </div>
                                                <div class="content">
                                                    <ul>
                                                        <li>
                                                            <h5>090-484-8080</h5>
                                                            <span>PHONE NUMBER</span>
                                                        </li>
                                                        <li>
                                                            <h5>info@company.com</h5>
                                                            <span>EMAIL ADDRESS</span>
                                                        </li>
                                                        <li>
                                                            <h5>123 Aenean id posuere dui,
                                                                <br>Praesent laoreet 10660</h5>
                                                            <span>STREET ADDRESS</span>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        </div>
                                        </div>
                                        </div>

                                        <div class="col-lg-12">
                                            <div id="map">
                                                <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                                        width="100%" height="450px" frameborder="0" style="border:0"
                                                        allowfullscreen></iframe>
                                            </div>
                                        </div>

                                        </div>
                                        </div>
                                        </section>
                                    {% else %}
                                        <div class="content">
                                            <p class="alert alert-danger">If you wana post contact first<a
                                                    style="color: #000000"
                                                    href="{% url 'account:user_login' %}"> login </a> / <a
                                                    style="color: #000000"
                                                    href="{% url 'account:user_register' %}"> Register </a>
                                            </p>
                                        </div>
                                    {% endif %}

{% endblock %}