account/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='user_login'),
    path('logout/', views.logout, name='user_logout'),
    path('register/', views.Register.as_view(), name='user_register'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),

    path('home/', views.AccountHomeView.as_view(), name='home'),
    path('profile/edit/', views.profile_normal_user_view, name='profile-edit'),
    path('search/', views.article_search, name='search'),
    path('article/create', views.ArticleCreateView.as_view(), name='article-create'),
    path('article/update/<int:pk>', views.ArticleUpdateView.as_view(), name='article-update'),
    path('article/delete/<int:pk>', views.ArticleDeleteView.as_view(), name='article-delete'),
    path('profile', views.ProfileUpdateView.as_view(), name='profile'),

]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('detail/<slug:slug>', views.PostDetailView.as_view(), name='blog_detail'),
    path('list',views.PostListView.as_view(), name='blog_list'),
    path('category/<int:pk>', views.category_detail.as_view(), name='cat_list'),
    path('tag/<int:pk>', views.tag_detail.as_view(), name='tag_list'),
    path('comment/delete/<int:pk>/<slug:slug>', views.DeleteCommentView.as_view(), name='comment_delete'),
    path('search', views.SearchView.as_view(), name='search'),
    path('contact', views.ContactsView.as_view(), name='contact'),
    path('like/<slug:slug>/<int:pk>', views.LikeView.as_view(), name='like_article'),
    path('favorite/<int:id>', views.FavoriteView.as_view(), name='favorite_article'),
    path('favorite/list', views.FaveView.as_view(), name='favorite_list'),
    path('preview/<int:pk>', views.ArticlePreviewView.as_view(), name='article_preview'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('articles/', include('blogs.urls', namespace='blog')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/footer.html
{% load static %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/inc/head_references.html
{% load static %}
<!-- Bootstrap core CSS -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="icon" type="image/png" href=" {% static 'images/icons/favicon.ico' %} "/>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static "css/fontawesome.css" %}">
<link rel="stylesheet" href="{% static "css/templatemo-stand-blog.css" %}">
<link rel="stylesheet" href="{% static "css/owl.css" %}">
<!--

TemplateMo 551 Stand Blog

templates/inc/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>

    <title>Stand CSS Blog by TemplateMo</title>

    {% include 'inc/head_references.html' %}


<body>

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>

</div>
<!-- ***** Preloader End ***** -->

<!-- Header -->
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% with url_name=request.resolver_match.url_name %}
                        <li class="dropdown {% if url_name == 'home' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'home:home' %}">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        <li class="dropdown {% if url_name == 'about' %}active{% endif %}">
                            <a class="nav-link" href="about.html">About Us</a>
                        </li>
                        <li class="dropdown {% if url_name == 'blog_list' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'blog:blog_list' %}">All Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="post-details.html">Post Details</a>
                        </li>
                        <li class="dropdown {% if url_name == 'contact' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'blog:contact' %}">Contact Us</a>
                        </li>
                    {% endwith %}
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:user_login' %}?next={{ request.pach }}">
                                Login/Singup</a>
                            {% else %}
                            {% if user.profile.avatar %}
                                <span> <img src="{{ user.profile.image.url }}" style="border-radius: 30px;" width="30"
                                            height="30" alt="">

            </span>
                            {% else %}
                                <span> <img src="{% static 'images/image.png' %}" style="border-radius: 30px;"
                                            width="30" height="30" alt="">

            </span>
                            {% endif %}
                        {% if request.user.is_superuser or request.user.is_staff %}
                        	<a class="nav-link" href="{% url 'account:home' %}"

                        {% else %}
                            <a class="nav-link" href="{% url 'account:profile-edit' %}"
                        {% endif %}
                               data-placeholder="&#xf207;">{{ request.user.username }}</a>
                            <a class="nav-link"
                               href="{% url 'account:user_logout' %}?next={{ request.pach }}">logout</a>


                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

templates/inc/scripts.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/inc/sidebar.html
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>

                            <li>
                                {% for article in resent_article %}
                                    <a href="{% url 'blog:blog_detail' article.slug %}">
                                        <h5>{{ article.title }}</h5>
                                        <span>{{ article.created }}</span>

                                    </a>
                                {% endfor %}
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for category in categories %}
                                <li><a href="{% url 'blog:cat_list' category.id %}">- {{ category.title }} {{ category.categories.all.count }}</a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for tag in article.tag.all %}
                                <li><a href="{% url 'blog:tag_list' tag.id %}">{{ tag.title }} {{ tag.articles.count }}</a> </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/sidebar_home_listpost.html
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="{% url 'blog:search' %}">
                        <input type="text" name="q" value="{{ q }}" class="searchText" placeholder="type to search..."
                               autocomplete="on">
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>
                            <li>
                                {% for article in articles %}
                                    <a href="{% url 'blog:blog_detail' article.slug %}">
                                        <h5>{{ article.title }}</h5>
                                        <span>{{ article.created }}</span>

                                    </a>
                                {% endfor %}
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for category in categories %}
                                <li><a href="{% url 'blog:cat_list' category.id %}">- {{ category.title }} {{ category.categories.all.count }}</a></li>
                            {% endfor %}


                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for tag in tags %}
                                <li><a href="{% url 'blog:tag_list' tag.id %}">{{ tag.title }}  {{ tag.articles.all.count }}</a> </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/social_network_link_share.html
{% load social_share %}

<div class="col-6">
    <ul class="post-share">
        <li><i class="fa fa-share-alt"></i></li>
        <li>{% post_to_linkedin article.get_absolute_url "Share" %}</li>
        |
        <li>{% post_to_facebook article.get_absolute_url "Share Facebook" %}</li>
        |
        <li>{% post_to_whatsapp article.get_absolute_url "Share Whats app" %}</li>
        |
        <li>{% post_to_telegram article.get_absolute_url "Share Telegram" %}</li>

    </ul>
</div>